function blogData() {
    return [
        {
            "id": 0,
            "name": "Dealing with Anxiety When You're Sick\nRizza Bermio-Gonzalez\nTreating Anxiety\nNot long ago, my therapist asked me to think about my anxiety triggers. I thought about the multiple triggers that lead me to feel anxious, and I realized that one of them is illness, whether it is my own or that of someone I care about.\nContinue Reading",
            "TITLE": "Dealing with Anxiety When You're Sick",
            "TITLE_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/7/dealing-with-anxiety-when-youre-sick",
            "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Anxiety%20and%20Sick.jpg?itok=Jn9XDJWv",
            "IMAge_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/7/dealing-with-anxiety-when-youre-sick",
            "BRIEF": "<p>Not long ago, my therapist asked me to think about my anxiety triggers. I thought about the multiple triggers that lead me to feel anxious, and I realized that one of them is illness, whether it is my own or that of someone I care about.</p><p>A couple of years ago, at the height of the pandemic, I contracted COVID-19. This was before the vaccines and during the time that hospitalizations were high. Also, there was a lot less known about the virus, and so, when I became ill, it was very scary for me. Naturally, as someone who deals with chronic anxiety, I became very anxious, so much so that I also had panic attacks while I was sick.</p><p>Reflecting on when this happened, I realize that a lot of the anxiety I was dealing with was from this perceived lack of control I had over the situation. Because there were so many uncertainties at the time, I recall feeling terrified that I did not know what would happen next. I thrive on having a routine and following a specific schedule. When I was sick with COVID-19, I found that I was unable to follow my regular routine. Because of this, I felt like I was in the middle of this chaotic situation, and I couldn't quite grasp something that could keep me grounded.</p><p><h4>How I Deal with Anxiety and Illness</h4></p><p>This experience made something clear to me -- when a loved one or I am very sick, it is a major trigger for my anxiety. As a result, it is something I need to be prepared to cope with. Whenever I feel as though things are out of my control, I tend to feel anxious. Other than trying to take steps to prevent illness, being sick is simply something that we don't have control over in our bodies. And so, this loss of control is something that makes me extremely anxious.</p><p>Being sick is already difficult enough to deal with, but when you also deal with anxiety on top of illness, it becomes even more challenging. What's worse is that because anxiety makes it difficult for you to relax, and rest is critical when you are sick, anxiety isn't conducive to healing.</p><p>In order to deal with this, I identify what I do have control over and what I don't. I remind myself that illness is not something that you can control, and so I try to focus on what I am able to control. I try to use mindfulness techniques and stay present in the moment. I also try to deal with one day at a time instead of worrying about the next. Lastly, I lean on my support system. Sometimes vocalizing my fears and worries is what I need to do to help me feel better.</p>",
            "Author": "Rizza Bermio-Gonzalez",
            "Author_url": "https://www.healthyplace.com/blogs/treatinganxiety/2019/12/introduction-rizza-bermio-gonzalez-author-treating-anxiety",
            "Category": "Treating Anxiety",
            "Category_url": "https://www.healthyplace.com/blogs/treatinganxiety"
          },
        {
            "id": 1,
            "name": "What Is BIPOC Mental Health Month (MHM)?\nJuliet Jack\nSurviving Mental Health Stigma\nThis July marks the 14th anniversary of the Bebe Moore Campbell National Minority Mental Health Month, also known as Black, Indigenous, and People of Color Mental Health Month (BIPOC MHM). In a world that seemingly revolves around race, it's nearly impossible to ignore the stark disparities deeply rooted in minority and historically oppressed communities regarding mental health accessibility and stigma.\nContinue Reading",
            "TITLE": "What Is BIPOC Mental Health Month (MHM)?",
            "TITLE_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/what-is-bipoc-mental-health-month-mhm",
            "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/BIPOC%20mental%20health%20month.jpg?itok=Nv8S8tr0",
            "IMAge_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/what-is-bipoc-mental-health-month-mhm",
            "BRIEF": "This July marks the 14th anniversary of the Bebe Moore Campbell National Minority Mental Health Month, also known as Black, Indigenous, and People of Color Mental Health Month (BIPOC MHM). In a world that seemingly revolves around race, it's nearly impossible to ignore the stark disparities deeply rooted in minority and historically oppressed communities regarding mental health accessibility and stigma.",
            "Author": "Juliet Jack",
            "Author_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/1/introduction-to-juliet-jack-author-of-surviving-mental-health-stigma-blog",
            "Category": "Surviving Mental Health Stigma",
            "Category_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma"
          },
        {
          "id": 2,
          "name": "My Friendships Have Affected My Mental Health\nMartha Lueck\nGetting Through Tough Times\nOver the weekend, I had lunch with a friend I had not seen in five years. During part of our conversation, we discussed the importance of friendships. In this post, I will discuss my friendships at different stages of my life and how they have affected my mental health.\nContinue Reading",
          "TITLE": "My Friendships Have Affected My Mental Health",
          "TITLE_url": "https://www.healthyplace.com/blogs/toughtimes/2022/7/my-friendships-have-affected-my-mental-health",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Having-Fun-13-healthyplace.jpg?itok=ROHpCOyX",
          "IMAge_url": "https://www.healthyplace.com/blogs/toughtimes/2022/7/my-friendships-have-affected-my-mental-health",
          "BRIEF": "Over the weekend, I had lunch with a friend I had not seen in five years. During part of our conversation, we discussed the importance of friendships. In this post, I will discuss my friendships at different stages of my life and how they have affected my mental health.",
          "Author": "Martha Lueck",
          "Author_url": "https://www.healthyplace.com/blogs/toughtimes/2016/12/introduction-to-martha-lueck",
          "Category": "Getting Through Tough Times",
          "Category_url": "https://www.healthyplace.com/blogs/toughtimes"
        },
        {
          "id": 3,
          "name": "How to Ensure an Eating Disorder Will Not Ruin a Vacation\nMary-Elizabeth Schurrer\nSurviving ED\nI just returned from a two-week trip overseas to England, Scotland, and Ireland. I love to explore the beauty of this earth and immerse myself in all kinds of unique cultures, but if I am not careful, traveling will often coax my eating disorder back to the surface. While I do have quite an adventurous streak, I also tend to feel anxious when I deviate from my normal routine, which can open the door for a certain uninvited guest—otherwise known as my eating disorder—to hitch a ride on the trip. However, since I am not about to stop traveling, here are a few strategies I use in order to be sure this pesky eating disorder will not ruin my vacation.\nContinue Reading",
          "TITLE": "How to Ensure an Eating Disorder Will Not Ruin a Vacation",
          "TITLE_url": "https://www.healthyplace.com/blogs/survivinged/2022/7/how-to-ensure-an-eating-disorder-will-not-ruin-a-vacation",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/ensure%20eating%20disorder%20won%27t%20ruin%20vacation.jpg?itok=ezSxbZlb",
          "IMAge_url": "https://www.healthyplace.com/blogs/survivinged/2022/7/how-to-ensure-an-eating-disorder-will-not-ruin-a-vacation",
          "BRIEF": "I just returned from a two-week trip overseas to England, Scotland, and Ireland. I love to explore the beauty of this earth and immerse myself in all kinds of unique cultures, but if I am not careful, traveling will often coax my eating disorder back to the surface. While I do have quite an adventurous streak, I also tend to feel anxious when I deviate from my normal routine, which can open the door for a certain uninvited guest—otherwise known as my eating disorder—to hitch a ride on the trip. However, since I am not about to stop traveling, here are a few strategies I use in order to be sure this pesky eating disorder will not ruin my vacation.",
          "Author": "Mary-Elizabeth Schurrer",
          "Author_url": "https://www.healthyplace.com/blogs/survivinged/2017/09/introduction-to-mary-elizabeth-schurrer/",
          "Category": "Surviving ED",
          "Category_url": "https://www.healthyplace.com/blogs/survivinged"
        },
        {
          "id": 4,
          "name": "Maintaining Friendships When You Have Anxiety Is Hard\nShubhechha Dhar\nTreating Anxiety\nMaking new friends when you have anxiety is hard, but maintaining those friendships is even harder. As someone with social anxiety disorder, I used to struggle maintaining friends. These thoughts would cross my mind: Will I lose my friends if I refused to hang out with them too my times? Do my friends actually like me or are they just hanging out with me because they feel bad for me?\nContinue Reading",
          "TITLE": "Maintaining Friendships When You Have Anxiety Is Hard",
          "TITLE_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/7/maintaining-friendships-when-you-have-anxiety-is-hard",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Maintaining%20friendships%20when%20you%20have%20anxiety%20.jpg?itok=M-7mpNJa",
          "IMAge_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/7/maintaining-friendships-when-you-have-anxiety-is-hard",
          "BRIEF": "Making new friends when you have anxiety is hard, but maintaining those friendships is even harder. As someone with social anxiety disorder, I used to struggle maintaining friends. These thoughts would cross my mind: Will I lose my friends if I refused to hang out with them too my times? Do my friends actually like me or are they just hanging out with me because they feel bad for me?",
          "Author": "Shubhechha Dhar",
          "Author_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/3/introduction-to-shubhechha-dhar-new-author-of-treating-anxiety",
          "Category": "Treating Anxiety",
          "Category_url": "https://www.healthyplace.com/blogs/treatinganxiety"
        },
        {
          "id": 5,
          "name": "Recognize Marketing Tactics that Use Mental Health Stigma\nLaura A. Barton\nSurviving Mental Health Stigma\nThe basis of marketing is pretty simple: identify a problem your target customer is facing and offer a solution. In most cases, it’s effective, but, unfortunately, it’s also used in predatory marketing practices that don’t necessarily have a sound product or opportunity to offer. It’s important to be able to recognize mental health stigma used in marketing tactics in order to protect yourself from falling prey to them.\nContinue Reading",
          "TITLE": "Recognize Marketing Tactics that Use Mental Health Stigma",
          "TITLE_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/recognize-marketing-tactics-that-use-mental-health-stigma",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Recognize%20Marketing%20Tactics%20that%20Use%20Mental%20Health%20Stigma.jpg?itok=gdX1w3rt",
          "IMAge_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/recognize-marketing-tactics-that-use-mental-health-stigma",
          "BRIEF": "The basis of marketing is pretty simple: identify a problem your target customer is facing and offer a solution. In most cases, it’s effective, but, unfortunately, it’s also used in predatory marketing practices that don’t necessarily have a sound product or opportunity to offer. It’s important to be able to recognize mental health stigma used in marketing tactics in order to protect yourself from falling prey to them.",
          "Author": "Laura A. Barton",
          "Author_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2015/09/about-laura-barton",
          "Category": "Surviving Mental Health Stigma",
          "Category_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma"
        },
        {
          "id": 6,
          "name": "Using the Physiological Sigh to Manage Anxiety\nLiana M. Scott\nAnxiety-Schmanxiety\nLike most people, when I'm having a hard cry—very emotional, sometimes overwhelming—I do a double intake of breath. It's like a hiccup, but not. My therapist told me that this is called the physiological sigh and that it helps reduce stress by balancing oxygen and carbon dioxide levels in our bodies.\nContinue Reading",
          "TITLE": "Using the Physiological Sigh to Manage Anxiety",
          "TITLE_url": "https://www.healthyplace.com/blogs/anxiety-schmanxiety/2022/7/using-the-physiological-sigh-to-manage-anxiety",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/20220725_Physiological%20Sigh.jpg?itok=YtEGeKc0",
          "IMAge_url": "https://www.healthyplace.com/blogs/anxiety-schmanxiety/2022/7/using-the-physiological-sigh-to-manage-anxiety",
          "BRIEF": "Like most people, when I'm having a hard cry—very emotional, sometimes overwhelming—I do a double intake of breath. It's like a hiccup, but not. My therapist told me that this is called the physiological sigh and that it helps reduce stress by balancing oxygen and carbon dioxide levels in our bodies.",
          "Author": "Liana M. Scott",
          "Author_url": "https://www.healthyplace.com/blogs/anxiety-schmanxiety/2022/1/introduction-to-liana-m-scott-author-of-anxiety-schmanxiety-blog",
          "Category": "Anxiety-Schmanxiety",
          "Category_url": "https://www.healthyplace.com/blogs/anxiety-schmanxiety"
        },
        {
          "id": 7,
          "name": "Learning to Stop Over-Apologizing Because I Was Abused\nCheryl Wozny\nVerbal Abuse in Relationships\nIf there is one thing I have learned through countless hours of therapy, it is how I need to stop apologizing for everything. Although Canadians are very apologetic, this pattern is prevalent with verbal abuse victims even more so. My underlying desire to make everything better and have everyone be happy with the situation has built an unstable emotional foundation for my life.\nContinue Reading",
          "TITLE": "Learning to Stop Over-Apologizing Because I Was Abused",
          "TITLE_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2022/7/learning-to-stop-over-apologizing-because-i-was-abused",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Victims_of_abuse_apologize_more.jpeg?itok=oW7NF1Ib",
          "IMAge_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2022/7/learning-to-stop-over-apologizing-because-i-was-abused",
          "BRIEF": "If there is one thing I have learned through countless hours of therapy, it is how I need to stop apologizing for everything. Although Canadians are very apologetic, this pattern is prevalent with verbal abuse victims even more so. My underlying desire to make everything better and have everyone be happy with the situation has built an unstable emotional foundation for my life.",
          "Author": "Cheryl Wozny",
          "Author_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2020/12/introduction-to-cheryl-wozny-author-of-verbal-abuse-in-relationships",
          "Category": "Verbal Abuse in Relationships",
          "Category_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships"
        },
        {
          "id": 8,
          "name": "What Is BIPOC Mental Health Month (MHM)?\nJuliet Jack\nSurviving Mental Health Stigma\nThis July marks the 14th anniversary of the Bebe Moore Campbell National Minority Mental Health Month, also known as Black, Indigenous, and People of Color Mental Health Month (BIPOC MHM). In a world that seemingly revolves around race, it's nearly impossible to ignore the stark disparities deeply rooted in minority and historically oppressed communities regarding mental health accessibility and stigma.\nContinue Reading",
          "TITLE": "What Is BIPOC Mental Health Month (MHM)?",
          "TITLE_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/what-is-bipoc-mental-health-month-mhm",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/BIPOC%20mental%20health%20month.jpg?itok=Nv8S8tr0",
          "IMAge_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/what-is-bipoc-mental-health-month-mhm",
          "BRIEF": "This July marks the 14th anniversary of the Bebe Moore Campbell National Minority Mental Health Month, also known as Black, Indigenous, and People of Color Mental Health Month (BIPOC MHM). In a world that seemingly revolves around race, it's nearly impossible to ignore the stark disparities deeply rooted in minority and historically oppressed communities regarding mental health accessibility and stigma.",
          "Author": "Juliet Jack",
          "Author_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/1/introduction-to-juliet-jack-author-of-surviving-mental-health-stigma-blog",
          "Category": "Surviving Mental Health Stigma",
          "Category_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma"
        },
        {
          "id": 9,
          "name": "The Trauma of a Mass Shooting with Schizoaffective Anxiety\nElizabeth Caudy\nCreative Schizophrenia\nA parade celebrating Independence Day turned deadly when a barrage of shots rang out into the crowd. It was yet another trauma-causing mass shooting, but this time it was in Highland Park, a Chicago suburb just a few towns north of me on the North Shore.\nContinue Reading",
          "TITLE": "The Trauma of a Mass Shooting with Schizoaffective Anxiety",
          "TITLE_url": "https://www.healthyplace.com/blogs/creativeschizophrenia/2022/7/the-trauma-of-a-mass-shooting-with-schizoaffective-anxiety",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/schizoaffective%20anxiety%20trauma%20mass%20shooting.jpg?itok=l0gzZRYY",
          "IMAge_url": "https://www.healthyplace.com/blogs/creativeschizophrenia/2022/7/the-trauma-of-a-mass-shooting-with-schizoaffective-anxiety",
          "BRIEF": "A parade celebrating Independence Day turned deadly when a barrage of shots rang out into the crowd. It was yet another trauma-causing mass shooting, but this time it was in Highland Park, a Chicago suburb just a few towns north of me on the North Shore.",
          "Author": "Elizabeth Caudy",
          "Author_url": "https://www.healthyplace.com/blogs/creativeschizophrenia/2015/01/about-elizabeth-caudy/",
          "Category": "Creative Schizophrenia",
          "Category_url": "https://www.healthyplace.com/blogs/creativeschizophrenia"
        },
        {
          "id": 10,
          "name": "The Winding Road to Self-Harm Recovery\nKim Berkley\nSpeaking Out About Self Injury\nThe road to self-harm recovery isn't always an easy path to walk, and it's often full of unexpected twists and detours.\nContinue Reading",
          "TITLE": "The Winding Road to Self-Harm Recovery",
          "TITLE_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2022/7/the-winding-road-to-self-harm-recovery",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-06/road%20to%20recovery%20self%20harm.jpg?itok=RtIl4PpM",
          "IMAge_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2022/7/the-winding-road-to-self-harm-recovery",
          "BRIEF": "The road to self-harm recovery isn't always an easy path to walk, and it's often full of unexpected twists and detours.",
          "Author": "Kim Berkley",
          "Author_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2020/2/introduction-kim-berkley-author-speaking-out-about-self-injury",
          "Category": "Speaking Out About Self Injury",
          "Category_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury"
        },
        {
          "id": 11,
          "name": "The Winding Road Through Self-Harm Recovery\nKim Berkley\nSpeaking Out About Self Injury\nThe road to self-harm recovery isn't always an easy path to walk, and it's often full of unexpected twists and detours.\nContinue Reading",
          "TITLE": "The Winding Road Through Self-Harm Recovery",
          "TITLE_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2022/7/the-winding-road-through-self-harm-recovery",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-06/road%20to%20recovery%20self%20harm.jpg?itok=RtIl4PpM",
          "IMAge_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2022/7/the-winding-road-through-self-harm-recovery",
          "BRIEF": "The road to self-harm recovery isn't always an easy path to walk, and it's often full of unexpected twists and detours.",
          "Author": "Kim Berkley",
          "Author_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2020/2/introduction-kim-berkley-author-speaking-out-about-self-injury",
          "Category": "Speaking Out About Self Injury",
          "Category_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury"
        },
        {
          "id": 12,
          "name": "Being More Assertive Can Build Self-Esteem\nWill Redmond\nBuilding Self Esteem\nOver the last couple of weeks, I've been working on a new character trait -- being more assertive. Low self-esteem often makes me feel like being assertive is a bad thing. It can feel like I'm outright mean when that's not the case.\nContinue Reading",
          "TITLE": "Being More Assertive Can Build Self-Esteem",
          "TITLE_url": "https://www.healthyplace.com/blogs/buildingselfesteem/2022/7/being-more-assertive-can-build-self-esteem",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/self%20esteem%20assertiveness.jpg?itok=hkjS1cc0",
          "IMAge_url": "https://www.healthyplace.com/blogs/buildingselfesteem/2022/7/being-more-assertive-can-build-self-esteem",
          "BRIEF": "Over the last couple of weeks, I've been working on a new character trait -- being more assertive. Low self-esteem often makes me feel like being assertive is a bad thing. It can feel like I'm outright mean when that's not the case.",
          "Author": "Will Redmond",
          "Author_url": "https://www.healthyplace.com/blogs/buildingselfesteem/2022/1/introduction-to-will-redmond-author-of-building-self-esteem",
          "Category": "Building Self Esteem",
          "Category_url": "https://www.healthyplace.com/blogs/buildingselfesteem"
        },
        {
          "id": 13,
          "name": "Binge Eating Disorder and the Fear of the Unknown\nEmma Parten\nBinge Eating Recovery\nWhen I struggle with disordered eating behavior, specifically binge eating disorder (BED), I am usually fixated on thinking about the future. Fear and worry dominate whenever I try to control my food intake or comfort myself with food. The fear of the unknown triggers my binge eating disorder symptoms.\nContinue Reading",
          "TITLE": "Binge Eating Disorder and the Fear of the Unknown",
          "TITLE_url": "https://www.healthyplace.com/blogs/bingeeatingrecovery/2022/7/binge-eating-disorder-and-the-fear-of-the-unknown",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/binge%20eating%20disorder-fear%20of%20unknown.jpg?itok=ElYbwxsc",
          "IMAge_url": "https://www.healthyplace.com/blogs/bingeeatingrecovery/2022/7/binge-eating-disorder-and-the-fear-of-the-unknown",
          "BRIEF": "When I struggle with disordered eating behavior, specifically binge eating disorder (BED), I am usually fixated on thinking about the future. Fear and worry dominate whenever I try to control my food intake or comfort myself with food. The fear of the unknown triggers my binge eating disorder symptoms.",
          "Author": "Emma Parten",
          "Author_url": "https://www.healthyplace.com/blogs/bingeeatingrecovery/2022/1/introduction-to-emma-parten-author-of-binge-eating-recovery",
          "Category": "Binge Eating Recovery",
          "Category_url": "https://www.healthyplace.com/blogs/bingeeatingrecovery"
        },
        {
          "id": 14,
          "name": "BPD Symptoms and the Physical Side Effects\nDesiree Brown\nMore than Borderline\nI recently went through a challenging period and didn't realize the seriousness of the events on my mental health until I physically reacted to my borderline personality disorder (BPD) symptoms. It's not uncommon that my body knows something is up before I do.\nContinue Reading",
          "TITLE": "BPD Symptoms and the Physical Side Effects",
          "TITLE_url": "https://www.healthyplace.com/blogs/borderline/2022/7/bpd-symptoms-and-the-physical-side-effects",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/BPD%20Symptoms.jpg?itok=GM5O4IMW",
          "IMAge_url": "https://www.healthyplace.com/blogs/borderline/2022/7/bpd-symptoms-and-the-physical-side-effects",
          "BRIEF": "I recently went through a challenging period and didn't realize the seriousness of the events on my mental health until I physically reacted to my borderline personality disorder (BPD) symptoms. It's not uncommon that my body knows something is up before I do.",
          "Author": "Desiree Brown",
          "Author_url": "https://www.healthyplace.com/blogs/borderline/2022/4/introduction-to-desiree-brown-new-author-of-more-than-borderline",
          "Category": "More than Borderline",
          "Category_url": "https://www.healthyplace.com/blogs/borderline"
        },
        {
          "id": 15,
          "name": "Dealing with Anxiety When You're Sick\nRizza Bermio-Gonzalez\nTreating Anxiety\nNot long ago, my therapist asked me to think about my anxiety triggers. I thought about the multiple triggers that lead me to feel anxious, and I realized that one of them is illness, whether it is my own or that of someone I care about.\nContinue Reading",
          "TITLE": "Dealing with Anxiety When You're Sick",
          "TITLE_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/7/dealing-with-anxiety-when-youre-sick",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Anxiety%20and%20Sick.jpg?itok=Jn9XDJWv",
          "IMAge_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/7/dealing-with-anxiety-when-youre-sick",
          "BRIEF": "Not long ago, my therapist asked me to think about my anxiety triggers. I thought about the multiple triggers that lead me to feel anxious, and I realized that one of them is illness, whether it is my own or that of someone I care about.",
          "Author": "Rizza Bermio-Gonzalez",
          "Author_url": "https://www.healthyplace.com/blogs/treatinganxiety/2019/12/introduction-rizza-bermio-gonzalez-author-treating-anxiety",
          "Category": "Treating Anxiety",
          "Category_url": "https://www.healthyplace.com/blogs/treatinganxiety"
        },
        {
          "id": 16,
          "name": "I Like Reading About Other People’s ADHD Experience\nMichael Thomas Kincella\nLiving with Adult ADHD\nLike almost everybody else on earth, I seek out like-minded people to interact with. Sometimes, I find like-minded people by accident. Sometimes, I encounter people afflicted by adult attention-deficit/hyperactivity disorder, and we share our ADHD experiences.\nContinue Reading",
          "TITLE": "I Like Reading About Other People’s ADHD Experience",
          "TITLE_url": "https://www.healthyplace.com/blogs/livingwithadultadhd/2022/7/i-like-reading-about-other-peoples-adhd-experience",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/ADHD%20Conversations.jpg?itok=jPX7HOtJ",
          "IMAge_url": "https://www.healthyplace.com/blogs/livingwithadultadhd/2022/7/i-like-reading-about-other-peoples-adhd-experience",
          "BRIEF": "Like almost everybody else on earth, I seek out like-minded people to interact with. Sometimes, I find like-minded people by accident. Sometimes, I encounter people afflicted by adult attention-deficit/hyperactivity disorder, and we share our ADHD experiences.",
          "Author": "Michael Thomas Kincella",
          "Author_url": "https://www.healthyplace.com/blogs/livingwithadultadhd/2022/2/introduction-to-michael-thomas-kincella-new-author-of-living-with-adult-adhd",
          "Category": "Living with Adult ADHD",
          "Category_url": "https://www.healthyplace.com/blogs/livingwithadultadhd"
        },
        {
          "id": 17,
          "name": "An Endless Urge to Cry\nNatasha Tracy\nBreaking Bipolar\nMany days I suffer from what feels like an endless urge to cry. I wake up, and the first thing I may have is an urge to cry. I make coffee -- same thing. I sit down to work, and the urge is still here. You'll note that, at this point, nothing has happened in my day to cause this; I simply have an undeniable urge to cry.\nContinue Reading",
          "TITLE": "An Endless Urge to Cry",
          "TITLE_url": "https://www.healthyplace.com/blogs/breakingbipolar/2022/7/an-endless-urge-to-cry",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/An%20Endless%20Urge%20to%20Cry.jpg?itok=FQZGrqvy",
          "IMAge_url": "https://www.healthyplace.com/blogs/breakingbipolar/2022/7/an-endless-urge-to-cry",
          "BRIEF": "Many days I suffer from what feels like an endless urge to cry. I wake up, and the first thing I may have is an urge to cry. I make coffee -- same thing. I sit down to work, and the urge is still here. You'll note that, at this point, nothing has happened in my day to cause this; I simply have an undeniable urge to cry.",
          "Author": "Natasha Tracy",
          "Author_url": "https://www.healthyplace.com/blogs/breakingbipolar/2010/05/natasha-tracy-author-breaking-bipolar-blog",
          "Category": "Breaking Bipolar",
          "Category_url": "https://www.healthyplace.com/blogs/breakingbipolar"
        },
        {
          "id": 18,
          "name": "Finding Happiness After Verbal Abuse\nCheryl Wozny\nVerbal Abuse in Relationships\nIf you have a past riddled with verbal abuse like me, you may know how difficult it is to find happiness in your life. Prolonged abuse may have changed how you perceive the world and the actions of those around you. You may be hesitant when someone is nice to you or feel unworthy of love and affection. However, everyone deserves a life of happiness, and it is possible.\nContinue Reading",
          "TITLE": "Finding Happiness After Verbal Abuse",
          "TITLE_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2022/7/finding-happiness-after-verbal-abuse",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Finding_Happiness_in_Everyday_Situations.jpg?itok=nkBOV1HP",
          "IMAge_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2022/7/finding-happiness-after-verbal-abuse",
          "BRIEF": "If you have a past riddled with verbal abuse like me, you may know how difficult it is to find happiness in your life. Prolonged abuse may have changed how you perceive the world and the actions of those around you. You may be hesitant when someone is nice to you or feel unworthy of love and affection. However, everyone deserves a life of happiness, and it is possible.",
          "Author": "Cheryl Wozny",
          "Author_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2020/12/introduction-to-cheryl-wozny-author-of-verbal-abuse-in-relationships",
          "Category": "Verbal Abuse in Relationships",
          "Category_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships"
        },
        {
          "id": 19,
          "name": "Feeling Guilty About Self-Harm Scars\nKim Berkley\nSpeaking Out About Self Injury\nFeeling guilty about self-harm scars isn't uncommon—but it isn't necessary, either. Accepting your scars takes time, but it's an important part of healing.\nContinue Reading",
          "TITLE": "Feeling Guilty About Self-Harm Scars",
          "TITLE_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2022/7/feeling-guilty-about-self-harm-scars",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-06/self%20harm%20scars%20guilt.jpg?itok=-wJqHCbv",
          "IMAge_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2022/7/feeling-guilty-about-self-harm-scars",
          "BRIEF": "Feeling guilty about self-harm scars isn't uncommon—but it isn't necessary, either. Accepting your scars takes time, but it's an important part of healing.",
          "Author": "Kim Berkley",
          "Author_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury/2020/2/introduction-kim-berkley-author-speaking-out-about-self-injury",
          "Category": "Speaking Out About Self Injury",
          "Category_url": "https://www.healthyplace.com/blogs/speakingoutaboutselfinjury"
        },
        {
          "id": 20,
          "name": "I Can't Stop Insulting Myself\nNatasha Tracy\nBreaking Bipolar\nI can't stop insulting myself. I'm depressed, and that's one of the things that I do when I'm depressed. The insults I say at myself are unbelievably harsh and things I would never say to anyone else. But even though I know that it's the depression, and even though I know that it's negative and harmful, I just can't stop insulting myself.\nContinue Reading",
          "TITLE": "I Can't Stop Insulting Myself",
          "TITLE_url": "https://www.healthyplace.com/blogs/breakingbipolar/2022/7/i-cant-stop-insulting-myself",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/I%20Can%27t%20Stop%20Insulting%20Myself.jpg?itok=QuxSa4IG",
          "IMAge_url": "https://www.healthyplace.com/blogs/breakingbipolar/2022/7/i-cant-stop-insulting-myself",
          "BRIEF": "I can't stop insulting myself. I'm depressed, and that's one of the things that I do when I'm depressed. The insults I say at myself are unbelievably harsh and things I would never say to anyone else. But even though I know that it's the depression, and even though I know that it's negative and harmful, I just can't stop insulting myself.",
          "Author": "Natasha Tracy",
          "Author_url": "https://www.healthyplace.com/blogs/breakingbipolar/2010/05/natasha-tracy-author-breaking-bipolar-blog",
          "Category": "Breaking Bipolar",
          "Category_url": "https://www.healthyplace.com/blogs/breakingbipolar"
        },
        {
          "id": 21,
          "name": "I Am Struggling To Accept My Double Depression Diagnosis\nMahevash Shaikh\nCoping with Depression\nJuly 12, 2022, was when my life changed forever. On this day, I got diagnosed with double depression, and I have been unable to come to terms with it. Even though I suspected it for a while, I don't know how to accept this as my reality. And I know it will be many moons before I do so.\nContinue Reading",
          "TITLE": "I Am Struggling To Accept My Double Depression Diagnosis",
          "TITLE_url": "https://www.healthyplace.com/blogs/copingwithdepression/2022/7/i-am-struggling-to-accept-my-double-depression-diagnosis",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/I%20Am%20Struggling%20To%20Accept%20My%20Double%20Depression%20Diagnosis.jpg?itok=bXFisX6L",
          "IMAge_url": "https://www.healthyplace.com/blogs/copingwithdepression/2022/7/i-am-struggling-to-accept-my-double-depression-diagnosis",
          "BRIEF": "July 12, 2022, was when my life changed forever. On this day, I got diagnosed with double depression, and I have been unable to come to terms with it. Even though I suspected it for a while, I don't know how to accept this as my reality. And I know it will be many moons before I do so.",
          "Author": "Mahevash Shaikh",
          "Author_url": "https://www.healthyplace.com/blogs/workandbipolarordepression/2019/5/mahevash-shaikh-author-work-bipolar-depression",
          "Category": "Coping with Depression",
          "Category_url": "https://www.healthyplace.com/blogs/copingwithdepression"
        },
        {
          "id": 22,
          "name": "BPD and Crisis: Part 1\nDesiree Brown\nMore than Borderline\nI tell myself that I write about borderline personality disorder (BPD) because I want to help others struggling with constant BPD and crisis. But, if I'm truly being honest here, I'm not writing to others — I'm writing to past me. The me who spent hours googling my behavior looking for answers. The me desperately seeking relief from my inner torment. A me I assume is long gone. This time, however, I want to write to a different me. This time, I want to write to the me that thinks she made it to the other side. The me that pretends to have some kind of authority on getting through BPD. This time I want to write to today's me.\nContinue Reading",
          "TITLE": "BPD and Crisis: Part 1",
          "TITLE_url": "https://www.healthyplace.com/blogs/borderline/2022/7/bpd-and-crisis-part-1",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/BPD%20Crisis.jpg?itok=pGKFxpiF",
          "IMAge_url": "https://www.healthyplace.com/blogs/borderline/2022/7/bpd-and-crisis-part-1",
          "BRIEF": "I tell myself that I write about borderline personality disorder (BPD) because I want to help others struggling with constant BPD and crisis. But, if I'm truly being honest here, I'm not writing to others — I'm writing to past me. The me who spent hours googling my behavior looking for answers. The me desperately seeking relief from my inner torment. A me I assume is long gone. This time, however, I want to write to a different me. This time, I want to write to the me that thinks she made it to the other side. The me that pretends to have some kind of authority on getting through BPD. This time I want to write to today's me.",
          "Author": "Desiree Brown",
          "Author_url": "https://www.healthyplace.com/blogs/borderline/2022/4/introduction-to-desiree-brown-new-author-of-more-than-borderline",
          "Category": "More than Borderline",
          "Category_url": "https://www.healthyplace.com/blogs/borderline"
        },
        {
          "id": 23,
          "name": "My Friendships Have Affected My Mental Health\nMartha Lueck\nGetting Through Tough Times\nOver the weekend, I had lunch with a friend I had not seen in five years. During part of our conversation, we discussed the importance of friendships. In this post, I will discuss my friendships at different stages of my life and how they have affected my mental health.\nContinue Reading",
          "TITLE": "My Friendships Have Affected My Mental Health",
          "TITLE_url": "https://www.healthyplace.com/blogs/toughtimes/2022/7/my-friendships-have-affected-my-mental-health",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Having-Fun-13-healthyplace.jpg?itok=ROHpCOyX",
          "IMAge_url": "https://www.healthyplace.com/blogs/toughtimes/2022/7/my-friendships-have-affected-my-mental-health",
          "BRIEF": "Over the weekend, I had lunch with a friend I had not seen in five years. During part of our conversation, we discussed the importance of friendships. In this post, I will discuss my friendships at different stages of my life and how they have affected my mental health.",
          "Author": "Martha Lueck",
          "Author_url": "https://www.healthyplace.com/blogs/toughtimes/2016/12/introduction-to-martha-lueck",
          "Category": "Getting Through Tough Times",
          "Category_url": "https://www.healthyplace.com/blogs/toughtimes"
        },
        {
          "id": 24,
          "name": "How to Ensure an Eating Disorder Will Not Ruin a Vacation\nMary-Elizabeth Schurrer\nSurviving ED\nI just returned from a two-week trip overseas to England, Scotland, and Ireland. I love to explore the beauty of this earth and immerse myself in all kinds of unique cultures, but if I am not careful, traveling will often coax my eating disorder back to the surface. While I do have quite an adventurous streak, I also tend to feel anxious when I deviate from my normal routine, which can open the door for a certain uninvited guest—otherwise known as my eating disorder—to hitch a ride on the trip. However, since I am not about to stop traveling, here are a few strategies I use in order to be sure this pesky eating disorder will not ruin my vacation.\nContinue Reading",
          "TITLE": "How to Ensure an Eating Disorder Will Not Ruin a Vacation",
          "TITLE_url": "https://www.healthyplace.com/blogs/survivinged/2022/7/how-to-ensure-an-eating-disorder-will-not-ruin-a-vacation",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/ensure%20eating%20disorder%20won%27t%20ruin%20vacation.jpg?itok=ezSxbZlb",
          "IMAge_url": "https://www.healthyplace.com/blogs/survivinged/2022/7/how-to-ensure-an-eating-disorder-will-not-ruin-a-vacation",
          "BRIEF": "I just returned from a two-week trip overseas to England, Scotland, and Ireland. I love to explore the beauty of this earth and immerse myself in all kinds of unique cultures, but if I am not careful, traveling will often coax my eating disorder back to the surface. While I do have quite an adventurous streak, I also tend to feel anxious when I deviate from my normal routine, which can open the door for a certain uninvited guest—otherwise known as my eating disorder—to hitch a ride on the trip. However, since I am not about to stop traveling, here are a few strategies I use in order to be sure this pesky eating disorder will not ruin my vacation.",
          "Author": "Mary-Elizabeth Schurrer",
          "Author_url": "https://www.healthyplace.com/blogs/survivinged/2017/09/introduction-to-mary-elizabeth-schurrer/",
          "Category": "Surviving ED",
          "Category_url": "https://www.healthyplace.com/blogs/survivinged"
        },
        {
          "id": 25,
          "name": "Maintaining Friendships When You Have Anxiety Is Hard\nShubhechha Dhar\nTreating Anxiety\nMaking new friends when you have anxiety is hard, but maintaining those friendships is even harder. As someone with social anxiety disorder, I used to struggle maintaining friends. These thoughts would cross my mind: Will I lose my friends if I refused to hang out with them too my times? Do my friends actually like me or are they just hanging out with me because they feel bad for me?\nContinue Reading",
          "TITLE": "Maintaining Friendships When You Have Anxiety Is Hard",
          "TITLE_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/7/maintaining-friendships-when-you-have-anxiety-is-hard",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Maintaining%20friendships%20when%20you%20have%20anxiety%20.jpg?itok=M-7mpNJa",
          "IMAge_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/7/maintaining-friendships-when-you-have-anxiety-is-hard",
          "BRIEF": "Making new friends when you have anxiety is hard, but maintaining those friendships is even harder. As someone with social anxiety disorder, I used to struggle maintaining friends. These thoughts would cross my mind: Will I lose my friends if I refused to hang out with them too my times? Do my friends actually like me or are they just hanging out with me because they feel bad for me?",
          "Author": "Shubhechha Dhar",
          "Author_url": "https://www.healthyplace.com/blogs/treatinganxiety/2022/3/introduction-to-shubhechha-dhar-new-author-of-treating-anxiety",
          "Category": "Treating Anxiety",
          "Category_url": "https://www.healthyplace.com/blogs/treatinganxiety"
        },
        {
          "id": 26,
          "name": "Recognize Marketing Tactics that Use Mental Health Stigma\nLaura A. Barton\nSurviving Mental Health Stigma\nThe basis of marketing is pretty simple: identify a problem your target customer is facing and offer a solution. In most cases, it’s effective, but, unfortunately, it’s also used in predatory marketing practices that don’t necessarily have a sound product or opportunity to offer. It’s important to be able to recognize mental health stigma used in marketing tactics in order to protect yourself from falling prey to them.\nContinue Reading",
          "TITLE": "Recognize Marketing Tactics that Use Mental Health Stigma",
          "TITLE_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/recognize-marketing-tactics-that-use-mental-health-stigma",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Recognize%20Marketing%20Tactics%20that%20Use%20Mental%20Health%20Stigma.jpg?itok=gdX1w3rt",
          "IMAge_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/recognize-marketing-tactics-that-use-mental-health-stigma",
          "BRIEF": "The basis of marketing is pretty simple: identify a problem your target customer is facing and offer a solution. In most cases, it’s effective, but, unfortunately, it’s also used in predatory marketing practices that don’t necessarily have a sound product or opportunity to offer. It’s important to be able to recognize mental health stigma used in marketing tactics in order to protect yourself from falling prey to them.",
          "Author": "Laura A. Barton",
          "Author_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2015/09/about-laura-barton",
          "Category": "Surviving Mental Health Stigma",
          "Category_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma"
        },
        {
          "id": 27,
          "name": "Using the Physiological Sigh to Manage Anxiety\nLiana M. Scott\nAnxiety-Schmanxiety\nLike most people, when I'm having a hard cry—very emotional, sometimes overwhelming—I do a double intake of breath. It's like a hiccup, but not. My therapist told me that this is called the physiological sigh and that it helps reduce stress by balancing oxygen and carbon dioxide levels in our bodies.\nContinue Reading",
          "TITLE": "Using the Physiological Sigh to Manage Anxiety",
          "TITLE_url": "https://www.healthyplace.com/blogs/anxiety-schmanxiety/2022/7/using-the-physiological-sigh-to-manage-anxiety",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/20220725_Physiological%20Sigh.jpg?itok=YtEGeKc0",
          "IMAge_url": "https://www.healthyplace.com/blogs/anxiety-schmanxiety/2022/7/using-the-physiological-sigh-to-manage-anxiety",
          "BRIEF": "Like most people, when I'm having a hard cry—very emotional, sometimes overwhelming—I do a double intake of breath. It's like a hiccup, but not. My therapist told me that this is called the physiological sigh and that it helps reduce stress by balancing oxygen and carbon dioxide levels in our bodies.",
          "Author": "Liana M. Scott",
          "Author_url": "https://www.healthyplace.com/blogs/anxiety-schmanxiety/2022/1/introduction-to-liana-m-scott-author-of-anxiety-schmanxiety-blog",
          "Category": "Anxiety-Schmanxiety",
          "Category_url": "https://www.healthyplace.com/blogs/anxiety-schmanxiety"
        },
        {
          "id": 29,
          "name": "Learning to Stop Over-Apologizing Because I Was Abused\nCheryl Wozny\nVerbal Abuse in Relationships\nIf there is one thing I have learned through countless hours of therapy, it is how I need to stop apologizing for everything. Although Canadians are very apologetic, this pattern is prevalent with verbal abuse victims even more so. My underlying desire to make everything better and have everyone be happy with the situation has built an unstable emotional foundation for my life.\nContinue Reading",
          "TITLE": "Learning to Stop Over-Apologizing Because I Was Abused",
          "TITLE_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2022/7/learning-to-stop-over-apologizing-because-i-was-abused",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/Victims_of_abuse_apologize_more.jpeg?itok=oW7NF1Ib",
          "IMAge_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2022/7/learning-to-stop-over-apologizing-because-i-was-abused",
          "BRIEF": "If there is one thing I have learned through countless hours of therapy, it is how I need to stop apologizing for everything. Although Canadians are very apologetic, this pattern is prevalent with verbal abuse victims even more so. My underlying desire to make everything better and have everyone be happy with the situation has built an unstable emotional foundation for my life.",
          "Author": "Cheryl Wozny",
          "Author_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships/2020/12/introduction-to-cheryl-wozny-author-of-verbal-abuse-in-relationships",
          "Category": "Verbal Abuse in Relationships",
          "Category_url": "https://www.healthyplace.com/blogs/verbalabuseinrelationships"
        },
        {
          "id": 30,
          "name": "What Is BIPOC Mental Health Month (MHM)?\nJuliet Jack\nSurviving Mental Health Stigma\nThis July marks the 14th anniversary of the Bebe Moore Campbell National Minority Mental Health Month, also known as Black, Indigenous, and People of Color Mental Health Month (BIPOC MHM). In a world that seemingly revolves around race, it's nearly impossible to ignore the stark disparities deeply rooted in minority and historically oppressed communities regarding mental health accessibility and stigma.\nContinue Reading",
          "TITLE": "What Is BIPOC Mental Health Month (MHM)?",
          "TITLE_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/what-is-bipoc-mental-health-month-mhm",
          "IMAge": "https://www.healthyplace.com/sites/default/files/styles/blog_listing/public/2022-07/BIPOC%20mental%20health%20month.jpg?itok=Nv8S8tr0",
          "IMAge_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/7/what-is-bipoc-mental-health-month-mhm",
          "BRIEF": "This July marks the 14th anniversary of the Bebe Moore Campbell National Minority Mental Health Month, also known as Black, Indigenous, and People of Color Mental Health Month (BIPOC MHM). In a world that seemingly revolves around race, it's nearly impossible to ignore the stark disparities deeply rooted in minority and historically oppressed communities regarding mental health accessibility and stigma.",
          "Author": "Juliet Jack",
          "Author_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma/2022/1/introduction-to-juliet-jack-author-of-surviving-mental-health-stigma-blog",
          "Category": "Surviving Mental Health Stigma",
          "Category_url": "https://www.healthyplace.com/blogs/survivingmentalhealthstigma"
        }
      ]
}

export default blogData;
